### ISSUE TITLE
안녕하세요!

### ISSUE THREAD

**Issue by kim-sung-jee** [geoje/MapleUnionTiler#2]
이번에 유니온에 적용되는 캐릭터가 40명에서 42명으로 늘어났습니다
시간남으시면 반영부탁드립니다!

**Comment by geoje** [comment]
메이플을 안하게 되어 몰랐네요.
의견 감사드립니다!! 반영해놓을게요~

**Comment by kim-sung-jee** [comment]
> 메이플을 안하게 되어 몰랐네요. 의견 감사드립니다!! 반영해놓을게요~

광운대 다니고잇슴니다...!! ㅎㅎ 멋지세요 저도 이런거 만들고싶은데 ㅠㅠ 존경합니당..
