### ISSUE TITLE
신 캐릭터 칼리 관련 에러

### ISSUE THREAD

**Issue by changwook987** [geoje/MapleUnionTiler#4]
신 캐릭터 칼리가 나왔지만 칼리의 직업군에 대한 패치가 없어 칼리 캐릭터가 무한 등록되는 버그가 있습니다.

**Comment by geoje** [comment]
메이플 업데이트에 잘 대응을 못했던 부분이 있었네요!
앞으로는 변경에 용의하도록 코드를 작성하여 다양한 `Contributor` 분들께서 `PR` 을 보내줄 수 있도록 개발에 임하겠습니다!

감사합니다! 😀
