### ISSUE TITLE
현재 캐릭터 등록이 동작하지 않습니다.

### ISSUE THREAD

**Issue by NYCH22** [geoje/MapleUnionTiler#5]
확인바랍니다.

**Comment by geoje** [comment]
기존 데이터 조회 방법인 `maple.gg` 에서의 `API` 요청 방식이 바뀌었어요!
빠른 대응이 불가능할 것 같아 `Repository` 는 `Archive` 시켰는데 이후에는 공식적으로 지원하는 `Nexon Open API` 를 활용하여 해당 오류는 대처가 용의해 질 것이며 앞으로 `PR` 또한 수용하여 개발에 임하도록 하겠습니다!
