### ISSUE TITLE
메이플 유니온 배치기 캐릭터 등록이 되지 않습니다.

### ISSUE THREAD

**Issue by SYsinabro** [geoje/MapleUnionTiler#6]
선생님 안녕하세요. 
메이플을 시작하며 유니온 배치가 너무 어려워 알아보다
선생님이 만드신 유니온 배치기를 발견하여 지금까지 잘 사용해오던 유저입니다.
그런데 최근에 캐릭터 등록이 동작하지 않아
이용 할 수 없습니다.
다른 배치기와 비교해 메이플, 제로 캐릭터, 유니온 레벨등
보다 정확하게 유니온을 비교 분석하여 관리 할 수 있었기 때문에 
이젠 이 유니온 배치기가 아니면 살 수 없는 몸이 되어버렸습니다,
부디 빠른 수정 부탁드립니다. 
감사합니다.

**Comment by geoje** [comment]
메이플 유니온 배치기를 정말 좋게 봐주시고 꾸준히 사용해 주셔서 감사드립니다!
원하시는 기능을 사용할 수 없었어서 정말 죄송스럽네요... 😭
현재 열심히 개발에 임하고 있으며, 앞으로는 지속가능한 서비스를 제공해드리며 유지보수에 용이하게 개발에 임하여 더 나은 서비스를 제공해드리도록 하겠습니다!

감사합니다! 😀
